AWSTemplateFormatVersion: 2010-09-09
Description: streaming image upload to s3
Transform:
- AWS::Serverless-2016-10-31
Resources:
  TestUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "2920-test-upload"
  UploadImageConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: UploadImage
      Destination:
        Type: AWS::S3::Bucket
        Arn: !Sub ${TestUploadBucket.Arn}
      Permissions:
        - Write
        - Read
  UploadImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.main
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          BUCKET: !Ref TestUploadBucket
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
